.PHONY: fmt
fmt:
	uv run --locked ruff format .
	uv run --locked ruff check --fix .

.PHONY: check
check:
	uv run --locked ruff format --check .
	uv run --locked ruff check .
	uv run --locked basedpyright ./src

.PHONY: tests
tests:
	uv run pytest -s -vvv \
		--cov=carthorse \
		--cov-branch \
		--cov-report=term-missing:skip-covered \
		--cov-fail-under=90 \
		--cov-report html:cov_html \
		--cov-report=xml:coverage.xml

# Re-build the carthorse-authored EXTENDED samples and diff them
# against the committed copies. Also re-asserts XSD validity and
# schematron-cleanliness on the regenerated bytes. Exits non-zero on
# drift so CI catches a stale fixture or a generator-only change.
.PHONY: synth-check
synth-check:
	uv run --locked python tools/build_synth_samples.py --check

# Cross-check every BT-/BG-/BR- citation in the carthorse sources,
# docstrings and docs against the JSON sidecars
# (``tools/business_terms.json`` and ``tools/business_rules.json``).
# Exits non-zero on any unknown id — catches typos / hallucinated
# spec references.
.PHONY: ids-check
ids-check:
	uv run --locked python tools/extract_business_terms.py
	uv run --locked python tools/extract_business_rules.py
	uv run --locked python tools/check_bt_br_ids.py

