.PHONY: fmt
fmt:
	uv run --locked ruff format .
	uv run --locked ruff check --fix .

.PHONY: check
check:
	uv run --locked ruff format --check .
	uv run --locked ruff check .
	uv run --locked basedpyright ./src

.PHONY: tests
tests:
	uv run pytest -s -vvv \
		--cov=carthorse \
		--cov-branch \
		--cov-report=term-missing:skip-covered \
		--cov-fail-under=90 \
		--cov-report html:cov_html \
		--cov-report=xml:coverage.xml

# Re-build the carthorse-authored EXTENDED samples and diff them
# against the committed copies. Also re-asserts XSD validity and
# schematron-cleanliness on the regenerated bytes. Exits non-zero on
# drift so CI catches a stale fixture or a generator-only change.
.PHONY: synth-check
synth-check:
	uv run --locked python tools/build_synth_samples.py --check

# Regenerate the BT/BG + BR sidecars, then run the schema-docs audit
# together with the BT-/BG-/BR- citation cross-check (``--check-citations``).
# The cross-check resolves every citation in the carthorse sources,
# docstrings and docs against the JSON sidecars
# (``tools/business_terms.json`` and ``tools/business_rules.json``) and
# exits non-zero on any unknown id — catches typos / hallucinated spec
# references.
.PHONY: ids-check
ids-check:
	uv run --locked python tools/extract_business_terms.py
	uv run --locked python tools/extract_business_rules.py
	uv run --locked python tools/check_schema_docs.py --check-citations

# Run the schema-docs audit with the full informational missing-attribute
# report. Not in CI — flags XSD children that aren't modelled yet
# (often EXTENDED-only attributes the maintainer hasn't picked up).
.PHONY: docs-coverage
docs-coverage:
	uv run --locked python tools/check_schema_docs.py --show-missing

