.PHONY: fmt
fmt:
	uv run --locked ruff format .
	uv run --locked ruff check --fix .

.PHONY: check
check:
	uv run --locked ruff format --check .
	uv run --locked ruff check .
	uv run --locked basedpyright ./src

.PHONY: tests
tests:
	uv run pytest -s -vvv \
		--cov=carthorse \
		--cov-branch \
		--cov-report=term-missing:skip-covered \
		--cov-fail-under=90 \
		--cov-report html:cov_html \
		--cov-report=xml:coverage.xml

# Re-build the carthorse-authored EXTENDED samples and diff them
# against the committed copies. Also re-asserts XSD validity and
# schematron-cleanliness on the regenerated bytes. Exits non-zero on
# drift so CI catches a stale fixture or a generator-only change.
.PHONY: synth-check
synth-check:
	uv run --locked python tools/build_synth_samples.py --check

