"""Round-trip coverage for the carthorse-authored synthetic EXTENDED
samples (``tests/samples/EXTENDED_synth_*.xml``).

These samples exercise EXTENDED-only structures the vendored ZF24 /
mustangproject corpus does not. ``test_xsd_validity`` and
``test_schematron_roundtrip`` already prove each file is XSD-valid and
schematron-clean (they glob ``EXTENDED_*.xml``); the tests here pin the
*semantic* round-trip — that carthorse parses each new structure into
the expected field values and re-emits the element on render.

The synthetic samples are regenerated by
``tools/build_synth_samples.py``; ``test_synth_samples_in_sync`` guards
against the committed copies drifting from that generator.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from lxml import etree

from carthorse.schema import Document

_SAMPLES = Path(__file__).parent / "samples"


def _load(name: str) -> Document:
    return Document.from_xml(etree.fromstring((_SAMPLES / name).read_bytes()))


def _rendered(doc: Document) -> str:
    return doc.to_xml().render(indent=True)


class TestAgentParties:
    """``EXTENDED_synth_agent_parties.xml`` — §4.1 header agent parties,
    delivery terms, and header quotation reference."""

    SAMPLE = "EXTENDED_synth_agent_parties.xml"

    def test_sales_agent_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.sales_agent is not None
        assert ag.sales_agent.name == "Handelsvertretung Meyer GmbH"
        assert ag.sales_agent.tax_registrations is not None
        assert ag.sales_agent.tax_registrations.id.id == "DE111222333"

    def test_buyer_tax_representative_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.buyer_tax_representative is not None
        assert ag.buyer_tax_representative.name == "Fiskalvertretung Schmidt KG"

    def test_buyer_agent_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.buyer_agent is not None
        assert ag.buyer_agent.name == "Einkaufsbüro Nord eG"

    def test_delivery_terms_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.delivery_terms is not None
        assert ag.delivery_terms.delivery_type_code == "FCA"
        assert ag.delivery_terms.relevant_location is not None
        assert ag.delivery_terms.relevant_location.name == "Hamburg Hafen"

    def test_header_quotation_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.quotation is not None
        assert ag.quotation.issuer_assigned_id == "ANG-2026-0042"
        assert ag.quotation.issue_date_time == date(2026, 5, 1)

    def test_roundtrip_emits_all_new_elements(self) -> None:
        out = _rendered(_load(self.SAMPLE))
        for tag in (
            "SalesAgentTradeParty",
            "BuyerTaxRepresentativeTradeParty",
            "BuyerAgentTradeParty",
            "ApplicableTradeDeliveryTerms",
            "DeliveryTypeCode",
            "RelevantTradeLocation",
            "QuotationReferencedDocument",
        ):
            assert tag in out, f"{tag} missing from re-rendered XML"


def test_synth_samples_in_sync() -> None:
    """The committed ``EXTENDED_synth_*.xml`` files match what
    ``tools/build_synth_samples.py`` produces — i.e. nobody hand-edited
    a generated fixture without updating the generator."""
    import sys

    sys.path.insert(0, str(Path(__file__).parent.parent))
    from tools.build_synth_samples import _BUILDERS

    for name, builder in _BUILDERS.items():
        committed = (_SAMPLES / name).read_bytes()
        assert committed == builder(), (
            f"{name} is out of sync with tools/build_synth_samples.py — "
            f"re-run `uv run python tools/build_synth_samples.py`"
        )
