"""Round-trip coverage for the getafix-authored synthetic EXTENDED
samples (``tests/samples/EXTENDED_synth_*.xml``).

These samples exercise EXTENDED-only structures the vendored ZF24 /
mustangproject corpus does not. ``test_xsd_validity`` and
``test_schematron_roundtrip`` already prove each file is XSD-valid and
schematron-clean (they glob ``EXTENDED_*.xml``); the tests here pin the
*semantic* round-trip — that getafix parses each new structure into
the expected field values and re-emits the element on render.

The synthetic samples are regenerated by
``tools/build_synth_samples.py``; ``test_synth_samples_in_sync`` guards
against the committed copies drifting from that generator.
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

from lxml import etree

from getafix.schema import Document

_SAMPLES = Path(__file__).parent / "samples"


def _load(name: str) -> Document:
    return Document.from_xml(etree.fromstring((_SAMPLES / name).read_bytes()))


def _rendered(doc: Document) -> str:
    return doc.to_xml().render(indent=True)


class TestAgentParties:
    """``EXTENDED_synth_agent_parties.xml`` — §4.1 header agent parties,
    delivery terms, and header quotation reference."""

    SAMPLE = "EXTENDED_synth_agent_parties.xml"

    def test_sales_agent_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.sales_agent is not None
        assert ag.sales_agent.name == "Handelsvertretung Meyer GmbH"
        assert ag.sales_agent.tax_registrations is not None
        assert ag.sales_agent.tax_registrations.id.id == "DE111222333"

    def test_buyer_tax_representative_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.buyer_tax_representative is not None
        assert ag.buyer_tax_representative.name == "Fiskalvertretung Schmidt KG"

    def test_buyer_agent_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.buyer_agent is not None
        assert ag.buyer_agent.name == "Einkaufsbüro Nord eG"

    def test_delivery_terms_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.delivery_terms is not None
        assert ag.delivery_terms.delivery_type_code == "FCA"
        assert ag.delivery_terms.relevant_location is not None
        assert ag.delivery_terms.relevant_location.name == "Hamburg Hafen"

    def test_header_quotation_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.agreement
        assert ag.quotation is not None
        assert ag.quotation.issuer_assigned_id == "ANG-2026-0042"
        assert ag.quotation.issue_date_time == date(2026, 5, 1)

    def test_roundtrip_emits_all_new_elements(self) -> None:
        out = _rendered(_load(self.SAMPLE))
        for tag in (
            "SalesAgentTradeParty",
            "BuyerTaxRepresentativeTradeParty",
            "BuyerAgentTradeParty",
            "ApplicableTradeDeliveryTerms",
            "DeliveryTypeCode",
            "RelevantTradeLocation",
            "QuotationReferencedDocument",
        ):
            assert tag in out, f"{tag} missing from re-rendered XML"


class TestSettlementParties:
    """``EXTENDED_synth_settlement_parties.xml`` — §4.3 settlement
    parties, advance payment, and term-specific payee."""

    SAMPLE = "EXTENDED_synth_settlement_parties.xml"

    def test_invoice_issuer_reference_parsed(self) -> None:
        s = _load(self.SAMPLE).trade.settlement
        assert s.invoice_issuer_reference == "BILLING-REF-2026-0815"

    def test_invoicer_invoicee_payer_parsed(self) -> None:
        s = _load(self.SAMPLE).trade.settlement
        assert s.invoicer is not None
        assert s.invoicer.name == "Konzern Shared Services GmbH"
        assert s.invoicee is not None
        assert s.invoicee.name == "Muster-Konzern Holding AG"
        assert s.payer is not None
        assert s.payer.name == "Nord Factoring AG"

    def test_advance_payment_parsed(self) -> None:
        s = _load(self.SAMPLE).trade.settlement
        assert s.advance_payments is not None
        adv = s.advance_payments[0]
        assert adv.paid_amount == Decimal("119.00")
        assert adv.received_date_time == date(2026, 4, 15)
        assert adv.included_trade_tax[0].calculated_amount == Decimal("19.00")
        assert adv.included_trade_tax[0].rate_applicable_percent == Decimal("19.00")
        assert adv.invoice_referenced_document is not None
        assert (
            adv.invoice_referenced_document.issuer_assigned_id == "PROFORMA-2026-0042"
        )

    def test_term_specific_payee_parsed(self) -> None:
        s = _load(self.SAMPLE).trade.settlement
        assert s.terms is not None
        assert s.terms[0].payee is not None
        assert s.terms[0].payee.name == "Nord Factoring AG - Inkasso"

    def test_roundtrip_emits_all_new_elements(self) -> None:
        out = _rendered(_load(self.SAMPLE))
        for tag in (
            "InvoiceIssuerReference",
            "InvoicerTradeParty",
            "InvoiceeTradeParty",
            "PayerTradeParty",
            "SpecifiedAdvancePayment",
            "PaidAmount",
            "FormattedReceivedDateTime",
            "IncludedTradeTax",
            "InvoiceSpecifiedReferencedDocument",
        ):
            assert tag in out, f"{tag} missing from re-rendered XML"


class TestProductLine:
    """``EXTENDED_synth_product_line.xml`` — §4.5 line/product
    enrichments on the first invoice line."""

    SAMPLE = "EXTENDED_synth_product_line.xml"

    def test_product_leaves_parsed(self) -> None:
        prod = _load(self.SAMPLE).trade.items[0].product
        assert prod.industry_assigned_id == "39121600"
        assert prod.model_id == "MOD-4711"
        assert prod.brand_name == "MusterBrand"
        assert prod.model_name == "EcoLine 200"
        assert prod.batch_id == ["LOT-2026-08", "LOT-2026-09"]

    def test_item_seller_parsed(self) -> None:
        ag = _load(self.SAMPLE).trade.items[0].agreement
        assert ag.item_seller is not None
        assert ag.item_seller.name == "Drittanbieter Direkt GmbH"

    def test_line_quantities_parsed(self) -> None:
        dl = _load(self.SAMPLE).trade.items[0].delivery
        assert dl.charge_free_quantity is not None
        assert dl.charge_free_quantity.value == Decimal("10.0000")
        assert dl.package_quantity is not None
        assert dl.package_quantity.unit_code == "XPK"
        assert dl.per_package_unit_quantity is not None
        assert dl.per_package_unit_quantity.value == Decimal("1000.0000")

    def test_line_ship_to_parsed(self) -> None:
        dl = _load(self.SAMPLE).trade.items[0].delivery
        assert dl.ship_to is not None
        assert dl.ship_to.name == "Filiale Süd"
        assert dl.ultimate_ship_to is not None
        assert dl.ultimate_ship_to.name == "Endkunde Karl Käufer"

    def test_roundtrip_emits_all_new_elements(self) -> None:
        out = _rendered(_load(self.SAMPLE))
        for tag in (
            "ModelID",
            "BrandName",
            "ModelName",
            "IndustryAssignedID",
            "ItemSellerTradeParty",
            "ChargeFreeQuantity",
            "PackageQuantity",
            "PerPackageUnitQuantity",
            "ShipToTradeParty",
            "UltimateShipToTradeParty",
        ):
            assert tag in out, f"{tag} missing from re-rendered XML"


def test_synth_samples_in_sync() -> None:
    """The committed ``EXTENDED_synth_*.xml`` files match what
    ``tools/build_synth_samples.py`` produces — i.e. nobody hand-edited
    a generated fixture without updating the generator."""
    import sys

    sys.path.insert(0, str(Path(__file__).parent.parent))
    from tools.build_synth_samples import _BUILDERS

    for name, builder in _BUILDERS.items():
        committed = (_SAMPLES / name).read_bytes()
        assert committed == builder(), (
            f"{name} is out of sync with tools/build_synth_samples.py — "
            f"re-run `uv run python tools/build_synth_samples.py`"
        )
